In [1]:
import pandas as pd
import numpy as np

In [2]:

data_path = "../data/raw/GlobalWeatherRepository.csv"
df = pd.read_csv(data_path)
df.head()

,timezone,country,location_name,latitude,longitude,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,NaN,Afghanistan,Kabul,34.52,69.18,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,NaN,Albania,Tirana,41.33,19.82,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,NaN,Algeria,Algiers,36.76,3.05,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,NaN,Andorra,Andorra La Vella,42.50,1.52,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,NaN,Angola,Luanda,-8.84,13.23,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [3]:
print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns)
df.info()

Dataset shape: (125501, 41)

Columns:
Index(['timezone', 'country', 'location_name', 'latitude', 'longitude',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125501 entries, 0 to 125500
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   timezone                      0 non-null       float64
 1   country                       125501 non-null  object
 2   location_name                 125501 non-null  object
 3   latitude                      125501 non-null  float64
 4   longitude                     125501 non-null  float64
 5   last_updated_epoch            125501 non-null  int64
 6   last_updated                  125501 non-null  object
 7   temperature_celsius           125501 non-null  float64
 8   temperature_fahrenheit        125501 non-null  float64
 9   condition_text                125501 non-null  object
 10  wind_mph                      125501 non-null  float64
 11  wind_kph                      125501 non-null  float64
 12  wind_degree                   125501 non-null  int64
 13  wind_direction                125501 non-null  object
 14  pressure_mb                   125501 non-null  float64
 15  pressure_in                   125501 non-null  float64
 16  precip_mm                     125501 non-null  float64
 17  precip_in                     125501 non-null  float64
 18  humidity                      125501 non-null  int64
 19  cloud                         125501 non-null  int64
 20  feels_like_celsius            125501 non-null  float64
 21  feels_like_fahrenheit         125501 non-null  float64
 22  visibility_km                 125501 non-null  float64
 23  visibility_miles              125501 non-null  float64
 24  uv_index                      125501 non-null  float64
 25  gust_mph                      125501 non-null  float64
 26  gust_kph                      125501 non-null  float64
 27  air_quality_Carbon_Monoxide   125501 non-null  float64
 28  air_quality_Ozone             125501 non-null  float64
 29  air_quality_Nitrogen_dioxide  125501 non-null  float64
 30  air_quality_Sulphur_dioxide   125501 non-null  float64
 31  air_quality_PM2.5             125501 non-null  float64
 32  air_quality_PM10              125501 non-null  float64
 33  air_quality_us-epa-index      125501 non-null  int64
 34  air_quality_gb-defra-index    125501 non-null  int64
 35  sunrise                       125501 non-null  object
 36  sunset                        125501 non-null  object
 37  moonrise                      125501 non-null  object
 38  moonset                       125501 non-null  object
 39  moon_phase                    125501 non-null  object
 40  moon_illumination             125501 non-null  int64
dtypes: float64(24), int64(7), object(10)
memory usage: 39.3+ MB

In [4]:
missing_values = df.isnull().sum()

In [5]:
# Filling numerical missing values with column mean
numeric_cols = df.select_dtypes(include=[np.number]).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

# Filling categorical missing values with 'Unknown'
categorical_cols = df.select_dtypes(include=["object"]).columns
df[categorical_cols] = df[categorical_cols].fillna("Unknown")

# Verifying missing values again
df.isnull().sum()

timezone                        125501
country                              0
location_name                        0
latitude                             0
longitude                            0
last_updated_epoch                   0
last_updated                         0
temperature_celsius                  0
temperature_fahrenheit               0
condition_text                       0
wind_mph                             0
wind_kph                             0
wind_degree                          0
wind_direction                       0
pressure_mb                          0
pressure_in                          0
precip_mm                            0
precip_in                            0
humidity                             0
cloud                                0
feels_like_celsius                   0
feels_like_fahrenheit                0
visibility_km                        0
visibility_miles                     0
uv_index                             0
gust_mph                             0
gust_kph                             0
air_quality_Carbon_Monoxide          0
air_quality_Ozone                    0
air_quality_Nitrogen_dioxide         0
air_quality_Sulphur_dioxide          0
air_quality_PM2.5                    0
air_quality_PM10                     0
air_quality_us-epa-index             0
air_quality_gb-defra-index           0
sunrise                              0
sunset                               0
moonrise                             0
moonset                              0
moon_phase                           0
moon_illumination                    0
dtype: int64

In [6]:
# Converting timestamp column to datetime
df["last_updated"] = pd.to_datetime(df["last_updated"], errors="coerce")

# Setting datetime column as index
df.set_index("last_updated", inplace=True)

# Extracted year and month for aggregation
df["year"] = df.index.year
df["month"] = df.index.month
df.head()

,timezone,country,location_name,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,...,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination,year,month
last_updated,,,,,,,,,,,,,,,,,,,,,
2024-05-16 13:15:00,NaN,Afghanistan,Kabul,34.52,69.18,1715849100,26.6,79.8,Partly Cloudy,8.3,...,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55,2024,5
2024-05-16 10:45:00,NaN,Albania,Tirana,41.33,19.82,1715849100,19.0,66.2,Partly cloudy,6.9,...,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55,2024,5
2024-05-16 09:45:00,NaN,Algeria,Algiers,36.76,3.05,1715849100,23.0,73.4,Sunny,9.4,...,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55,2024,5
2024-05-16 10:45:00,NaN,Andorra,Andorra La Vella,42.50,1.52,1715849100,6.3,43.3,Light drizzle,7.4,...,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55,2024,5
2024-05-16 09:45:00,NaN,Angola,Luanda,-8.84,13.23,1715849100,26.0,78.8,Partly cloudy,8.1,...,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55,2024,5

In [7]:
df.describe()

,timezone,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,...,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination,year,month
count,0.0,125501.000000,125501.000000,1.255010e+05,125501.000000,125501.000000,125501.000000,125501.000000,125501.000000,125501.000000,...,125501.000000,125501.000000,125501.000000,125501.000000,125501.000000,125501.000000,125501.000000,125501.000000,125501.000000,125501.000000
mean,NaN,19.194285,21.992818,1.743775e+09,21.573732,70.834471,8.066009,12.984579,169.175887,1014.055266,...,58.863922,15.239036,10.659911,24.573293,49.170688,1.709309,2.632417,49.347671,2024.724807,6.904160
std,NaN,24.425011,65.793975,1.611019e+07,9.611703,17.300940,7.360164,11.841975,103.466509,10.595466,...,31.103468,24.238412,36.875595,37.781243,151.632697,0.950215,2.471696,35.105818,0.598116,3.478667
min,NaN,-41.300000,-175.200000,1.715849e+09,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,...,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000,2024.000000,1.000000
25%,NaN,3.750000,-6.836100,1.729848e+09,16.300000,61.300000,3.800000,6.100000,80.000000,1010.000000,...,39.000000,1.665000,1.050000,7.100000,10.026000,1.000000,1.000000,14.000000,2024.000000,4.000000
50%,NaN,17.250000,23.240000,1.743758e+09,24.100000,75.400000,6.900000,11.200000,162.000000,1014.000000,...,56.000000,5.500000,2.450000,14.245000,20.250000,1.000000,2.000000,49.000000,2025.000000,7.000000
75%,NaN,40.400000,50.580000,1.757750e+09,28.100000,82.600000,11.000000,17.600000,256.000000,1018.000000,...,75.000000,17.760000,8.550000,28.120000,42.180000,2.000000,3.000000,84.000000,2025.000000,10.000000
max,NaN,64.150000,179.220000,1.771656e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,...,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000,2026.000000,12.000000

In [9]:
# cleaned dataset is saved 
processed_path =  "../data/processed/weather_cleaned.csv"

df.to_csv(processed_path, index=False)

print("Cleaned dataset saved to:", processed_path)

OSError: Cannot save file into a non-existent directory: '..\data\processed'

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

In [ ]:
plt.figure(figsize=(6,4))
sns.histplot(df["temperature_celsius"], bins=40, kde=True)
plt.title("Distribution of Temperature (°C)")
plt.xlabel("Temperature (°C)")
plt.ylabel("Frequency")
plt.show()

In [ ]:
monthly_temp = (
    df.groupby(["year", "month"])["temperature_celsius"]
    .mean()
    .reset_index()
)

plt.figure(figsize=(8,4))
sns.lineplot(
    data=monthly_temp,
    x="month",
    y="temperature_celsius",
    ci=None
)
plt.title("Average Monthly Temperature Trend")
plt.xlabel("Month")
plt.ylabel("Average Temperature (°C)")
plt.show()

In [ ]:
plt.figure(figsize=(6,4))
sns.histplot(df["precip_mm"], bins=40)
plt.title("Precipitation Distribution (mm)")
plt.xlabel("Precipitation (mm)")
plt.ylabel("Frequency")
plt.show()

In [ ]:
# Identify Seasons

def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Autumn"

df["season"] = df["month"].apply(get_season)

print("Season column added")
df[["year", "month", "season"]].head()

In [ ]:
# Country-wise Seasonal Analysis
# Select a country (change if needed)
country_name = "India"
country_df = df[df["country"] == country_name]

print(f"Filtered data for country: {country_name}")

In [ ]:
#  Seasonal Temperature Visualization

seasonal_temp = (
    country_df.groupby("season")["temperature_celsius"]
    .mean()
    .reindex(["Winter", "Spring", "Summer", "Autumn"])
    .reset_index()
)

plt.figure(figsize=(5, 3))
sns.barplot(
    data=seasonal_temp,
    x="season",
    y="temperature_celsius"
)
plt.title(f"Average Seasonal Temperature in {country_name}")
plt.xlabel("Season")
plt.ylabel("Average Temperature (°C)")
plt.show()

In [ ]:
#  Seasonal Precipitation Visualization

seasonal_rain = (
    country_df.groupby("season")["precip_mm"]
    .mean()
    .reindex(["Winter", "Spring", "Summer", "Autumn"])
    .reset_index()
)

plt.figure(figsize=(5, 3))
sns.barplot(
    data=seasonal_rain,
    x="season",
    y="precip_mm"
)
plt.title(f"Average Seasonal Precipitation in {country_name}")
plt.xlabel("Season")
plt.ylabel("Precipitation (mm)")
plt.show()

In [ ]:
# Save Final Dataset with Seasons

final_path = "../data/processed/weather_cleaned_with_seasons.csv"
df.to_csv(final_path, index=False)

print("Final dataset with seasons saved to:", final_path)